apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      initContainers:
      - name: linkerd-wait
        image: busybox
        command: ['sh', '-c', 'until nc -z linkerd-dst.linkerd.svc.cluster.local 8086; do echo waiting for linkerd; sleep 5; done;']
      - name: wait-for-dependencies
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: analyzer
        image: mehrdadfordobadi/kapitalism-analyzer
        ports:
        - containerPort: 8110
        env:
        - name: TARGET_ENV
          value: "test"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /logs
      volumes:
      - name: config
        configMap:
          name: analyzer-config
      - name: logs
        emptyDir: {}