# receiver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      initContainers:
      - name: linkerd-wait
        image: busybox
        command: ['sh', '-c', 'until nc -z linkerd-dst.linkerd.svc.cluster.local 8086; do echo waiting for linkerd; sleep 5; done;']
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'timeout=90; while [ $timeout -gt 0 ] && ! nc -z kafka 9092; do echo "waiting for kafka ($timeout secs remaining)"; sleep 5; timeout=$((timeout-5)); done; if [ $timeout -le 0 ]; then echo "Kafka connection timeout"; exit 1; fi']
      containers:
      - name: receiver
        image: mehrdadfordobadi/kapitalism-receiver
        ports:
        - containerPort: 8080
        env:
        - name: TARGET_ENV
          value: "test"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /logs
      volumes:
      - name: config
        configMap:
          name: receiver-config
      - name: logs
        emptyDir: {}