apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-service
  template:
    metadata:
      labels:
        app: processing-service
    spec:
      containers:
      - name: processing-service
        image: mehrdadfordobadi/cap-service
        ports:
        - containerPort: 8100
        env:
        - name: TARGET_ENV
          value: "test"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /logs
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: processing-config
      - name: logs
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: processing-data