events:
  hostname: kafka
  port: 9092
  topic: events

kafka:
  max_retries: 3
  retry_delay: 5

datastore:
  filename: "/data/anomalies.json"

anomaly:
  thresholds:
    price_max: 3000
    stock_min: 10