# Updated kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace (modified with Linkerd annotation)
  - namespaces/e-commerce.yml
  
  # Linkerd Service Profiles - Add these before your applications
  - linkerd/service-profiles/receiver-profile.yaml
  - linkerd/service-profiles/data-storage-profile.yaml
  - linkerd/service-profiles/processing-profile.yaml
  - linkerd/service-profiles/analyzer-profile.yaml
  - linkerd/service-profiles/anomaly-profile.yaml
  
  # ConfigMaps
  - configmaps/configmaps.yml
  
  # Infrastructure
  - events/zookeeper.yml
  - events/kafka.yml
  - databases/mysql/mysql.yml
  # - databases/mysql/hpa.yml
  
  # Applications
  - application/receiver/deployment.yml
  - application/receiver/service.yml
  - application/receiver/hpa.yml 
  - application/data-storage/deployment.yml
  - application/data-storage/service.yml
  - application/data-storage/hpa.yml
  - application/processing/deployment.yml
  - application/processing/service.yml
  - application/processing/pvc.yml
  - application/processing/hpa.yml
  - application/analyzer/deployment.yml
  - application/analyzer/service.yml
  - application/analyzer/hpa.yml
  - application/anamoly-detector/deployment.yml
  - application/anamoly-detector/service.yml
  - application/anamoly-detector/pvc.yml
  - application/anamoly-detector/hpa.yml
  - application/dashboard-ui/deployment.yml
  - application/dashboard-ui/service.yml
  
  # Ingress
  - ingress/ingress.yml
  - ingress/linkerd-viz-ingress.yml