version: 1
datastore:
  user: <your username>
  password: <your password>
  hostname: mysql
  port: 3306
  db: <your database name>
events:
  hostname: kafka
  port: 9092
  topic: events
kafka:
  max_retries: 3
  retry_delay: 5