apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: processing-service.ecommerce.svc.cluster.local
  namespace: ecommerce
spec:
  routes:
    - name: get-stats
      condition:
        method: GET
        pathRegex: /processing/stats
      timeout: "500ms"